server:
  port: 8770
eureka:  #注册中心
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8660/eureka/
spring:
  application:
    name: order-service
#PRODUCT-SERVICE:
  #ribbon:
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule